### ISSUE TITLE
BpmnXML转JSON

### ISSUE THREAD

**Issue by zhoujh001** [hoslay757/ddei-editor#1]
有没有提供将flowable的xml文件转为json渲染的方法？或者是能否直接加载xml数据？

**Comment by hoslay757** [comment]
具体说说你的需求吧，下一步计划要xml导入渲染的功能



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Flush ***@***.***&gt;
发送时间: 2024年11月22日 08:15
收件人: hoslay757/ddei-editor ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [hoslay757/ddei-editor] BpmnXML转JSON (Issue #1)

**Comment by zhoujh001** [comment]
我使用Flowable流程设计工具设计好了流程，xml保存在了数据库中。前端我想使用DFlow展示图形界面，DFlow是否可以直接加载xml内容展示？我看文档里好像只能是加载json数据和将json转换为xml，没有将xml转换为json或者直接加载xml数据的方法。

**Comment by hoslay757** [comment]
V1.0.0版本确实没有开发这个功能。Flowable生成的XML应该也是在BPMN基础上扩展的，本来打算后面来做这个功能。你急不？

**Comment by hoslay757** [comment]
能否发点测试数据过来？方便我们开发的时候可以验证结果。或者加qq 3697355039，我们私聊。

**Comment by zhoujh001** [comment]
公司不能使用qq，我直接发一个xml的数据吧
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:flowable="http://flowable.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.flowable.org/processdef" exporter="Flowable Open Source Modeler" exporterVersion="6.8.0">
  <process id="demo_qjlc" name="案例-请假申请流程" isExecutable="true">
    <documentation>测试案例1</documentation>
    <startEvent id="startEvent1" name="启动" flowable:initiator="INITIATOR" flowable:formFieldValidation="true"></startEvent>
    <userTask id="sqr" name="申请人" flowable:assignee="${INITIATOR}" flowable:formFieldValidation="true">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-EEF0DA1F-554E-4439-920E-0382841D7DE2" sourceRef="startEvent1" targetRef="sqr"></sequenceFlow>
    <userTask id="leader" name="主管" flowable:assignee="#{leader}" flowable:formFieldValidation="true">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
      <multiInstanceLoopCharacteristics isSequential="false" flowable:collection="${userService.getUser(execution.processInstanceId,execution.activityId)}" flowable:elementVariable="leader">
        <extensionElements></extensionElements>
        <completionCondition>${nrOfCompletedInstances &gt;= 1 }</completionCondition>
      </multiInstanceLoopCharacteristics>
    </userTask>
    <sequenceFlow id="sid-5DE8C566-4721-456A-9240-CF4BF3DC7A61" sourceRef="sqr" targetRef="leader"></sequenceFlow>
    <userTask id="hr" name="HR" flowable:assignee="lisi" flowable:formFieldValidation="true">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <endEvent id="sid-B951D5DB-EA64-4CD3-8F35-6463CA83A154" name="归档"></endEvent>
    <exclusiveGateway id="sid-38DE5F46-A270-4060-87D2-3DB97997B861"></exclusiveGateway>
    <sequenceFlow id="sid-D0666311-783F-49EC-95F7-13C648383566" sourceRef="leader" targetRef="sid-38DE5F46-A270-4060-87D2-3DB97997B861"></sequenceFlow>
    <sequenceFlow id="sid-ADD2E384-E8CC-4136-B881-93CFDC340A4E" sourceRef="hr" targetRef="sid-B951D5DB-EA64-4CD3-8F35-6463CA83A154"></sequenceFlow>
    <userTask id="leader2" name="最高主管" flowable:assignee="wangwu" flowable:formFieldValidation="true">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-753BBA2E-1D21-41EA-B44F-E8A0CDEE3D17" name="请假天数&lt;7" sourceRef="sid-38DE5F46-A270-4060-87D2-3DB97997B861" targetRef="hr">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[#{days < 7}]]></conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="sid-5F44C7A8-94DB-4EA3-A77F-5DF3092F1C56" name="请假天数&gt;=7" sourceRef="sid-38DE5F46-A270-4060-87D2-3DB97997B861" targetRef="leader2">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${days >= 7}]]></conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="sid-6A8F54F5-165A-430F-A218-F8B6A054B784" sourceRef="leader2" targetRef="hr"></sequenceFlow>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_demo_qjlc">
    <bpmndi:BPMNPlane bpmnElement="demo_qjlc" id="BPMNPlane_demo_qjlc">
      <bpmndi:BPMNShape bpmnElement="startEvent1" id="BPMNShape_startEvent1">
        <omgdc:Bounds height="30.0" width="30.0" x="120.0" y="145.625"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sqr" id="BPMNShape_sqr">
        <omgdc:Bounds height="80.0" width="100.0" x="195.0" y="120.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="leader" id="BPMNShape_leader">
        <omgdc:Bounds height="80.0" width="100.0" x="330.0" y="120.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="hr" id="BPMNShape_hr">
        <omgdc:Bounds height="80.0" width="100.0" x="645.0" y="120.625"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-B951D5DB-EA64-4CD3-8F35-6463CA83A154" id="BPMNShape_sid-B951D5DB-EA64-4CD3-8F35-6463CA83A154">
        <omgdc:Bounds height="28.0" width="28.0" x="870.0" y="146.625"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-38DE5F46-A270-4060-87D2-3DB97997B861" id="BPMNShape_sid-38DE5F46-A270-4060-87D2-3DB97997B861">
        <omgdc:Bounds height="40.0" width="40.0" x="475.0" y="140.625"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="leader2" id="BPMNShape_leader2">
        <omgdc:Bounds height="80.0" width="100.0" x="445.0" y="315.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sid-EEF0DA1F-554E-4439-920E-0382841D7DE2" id="BPMNEdge_sid-EEF0DA1F-554E-4439-920E-0382841D7DE2" flowable:sourceDockerX="15.0" flowable:sourceDockerY="15.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="149.94976375101032" y="160.53977407408564"></omgdi:waypoint>
        <omgdi:waypoint x="194.99999999999565" y="160.28380681818183"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-D0666311-783F-49EC-95F7-13C648383566" id="BPMNEdge_sid-D0666311-783F-49EC-95F7-13C648383566" flowable:sourceDockerX="50.0" flowable:sourceDockerY="40.0" flowable:targetDockerX="20.0" flowable:targetDockerY="20.0">
        <omgdi:waypoint x="429.95000000000005" y="160.27146739130436"></omgdi:waypoint>
        <omgdi:waypoint x="475.0672391445236" y="160.5168918918919"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-5F44C7A8-94DB-4EA3-A77F-5DF3092F1C56" id="BPMNEdge_sid-5F44C7A8-94DB-4EA3-A77F-5DF3092F1C56" flowable:sourceDockerX="20.0" flowable:sourceDockerY="20.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="495.0" y="180.5698708060162"></omgdi:waypoint>
        <omgdi:waypoint x="495.0" y="315.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-ADD2E384-E8CC-4136-B881-93CFDC340A4E" id="BPMNEdge_sid-ADD2E384-E8CC-4136-B881-93CFDC340A4E" flowable:sourceDockerX="50.0" flowable:sourceDockerY="40.0" flowable:targetDockerX="14.0" flowable:targetDockerY="14.0">
        <omgdi:waypoint x="744.9499999999675" y="160.625"></omgdi:waypoint>
        <omgdi:waypoint x="870.0" y="160.625"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-753BBA2E-1D21-41EA-B44F-E8A0CDEE3D17" id="BPMNEdge_sid-753BBA2E-1D21-41EA-B44F-E8A0CDEE3D17" flowable:sourceDockerX="20.0" flowable:sourceDockerY="20.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="514.9450149924147" y="160.625"></omgdi:waypoint>
        <omgdi:waypoint x="645.0" y="160.625"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-5DE8C566-4721-456A-9240-CF4BF3DC7A61" id="BPMNEdge_sid-5DE8C566-4721-456A-9240-CF4BF3DC7A61" flowable:sourceDockerX="50.0" flowable:sourceDockerY="40.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="294.9499999999527" y="160.0"></omgdi:waypoint>
        <omgdi:waypoint x="329.99999999997203" y="160.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-6A8F54F5-165A-430F-A218-F8B6A054B784" id="BPMNEdge_sid-6A8F54F5-165A-430F-A218-F8B6A054B784" flowable:sourceDockerX="50.0" flowable:sourceDockerY="40.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="536.1061093247588" y="315.0"></omgdi:waypoint>
        <omgdi:waypoint x="653.8424437299035" y="200.575"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>

**Comment by zhoujh001** [comment]
公司不能用qq，我直接发xml吧
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:flowable="http://flowable.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.flowable.org/processdef" exporter="Flowable Open Source Modeler" exporterVersion="6.8.0">
  <process id="demo_qjlc" name="案例-请假申请流程" isExecutable="true">
    <documentation>测试案例1</documentation>
    <startEvent id="startEvent1" name="启动" flowable:initiator="INITIATOR" flowable:formFieldValidation="true"></startEvent>
    <userTask id="sqr" name="申请人" flowable:assignee="${INITIATOR}" flowable:formFieldValidation="true">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-EEF0DA1F-554E-4439-920E-0382841D7DE2" sourceRef="startEvent1" targetRef="sqr"></sequenceFlow>
    <userTask id="leader" name="主管" flowable:assignee="#{leader}" flowable:formFieldValidation="true">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
      <multiInstanceLoopCharacteristics isSequential="false" flowable:collection="${userService.getUser(execution.processInstanceId,execution.activityId)}" flowable:elementVariable="leader">
        <extensionElements></extensionElements>
        <completionCondition>${nrOfCompletedInstances &gt;= 1 }</completionCondition>
      </multiInstanceLoopCharacteristics>
    </userTask>
    <sequenceFlow id="sid-5DE8C566-4721-456A-9240-CF4BF3DC7A61" sourceRef="sqr" targetRef="leader"></sequenceFlow>
    <userTask id="hr" name="HR" flowable:assignee="lisi" flowable:formFieldValidation="true">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <endEvent id="sid-B951D5DB-EA64-4CD3-8F35-6463CA83A154" name="归档"></endEvent>
    <exclusiveGateway id="sid-38DE5F46-A270-4060-87D2-3DB97997B861"></exclusiveGateway>
    <sequenceFlow id="sid-D0666311-783F-49EC-95F7-13C648383566" sourceRef="leader" targetRef="sid-38DE5F46-A270-4060-87D2-3DB97997B861"></sequenceFlow>
    <sequenceFlow id="sid-ADD2E384-E8CC-4136-B881-93CFDC340A4E" sourceRef="hr" targetRef="sid-B951D5DB-EA64-4CD3-8F35-6463CA83A154"></sequenceFlow>
    <userTask id="leader2" name="最高主管" flowable:assignee="wangwu" flowable:formFieldValidation="true">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-753BBA2E-1D21-41EA-B44F-E8A0CDEE3D17" name="请假天数&lt;7" sourceRef="sid-38DE5F46-A270-4060-87D2-3DB97997B861" targetRef="hr">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[#{days < 7}]]></conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="sid-5F44C7A8-94DB-4EA3-A77F-5DF3092F1C56" name="请假天数&gt;=7" sourceRef="sid-38DE5F46-A270-4060-87D2-3DB97997B861" targetRef="leader2">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${days >= 7}]]></conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="sid-6A8F54F5-165A-430F-A218-F8B6A054B784" sourceRef="leader2" targetRef="hr"></sequenceFlow>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_demo_qjlc">
    <bpmndi:BPMNPlane bpmnElement="demo_qjlc" id="BPMNPlane_demo_qjlc">
      <bpmndi:BPMNShape bpmnElement="startEvent1" id="BPMNShape_startEvent1">
        <omgdc:Bounds height="30.0" width="30.0" x="120.0" y="145.625"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sqr" id="BPMNShape_sqr">
        <omgdc:Bounds height="80.0" width="100.0" x="195.0" y="120.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="leader" id="BPMNShape_leader">
        <omgdc:Bounds height="80.0" width="100.0" x="330.0" y="120.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="hr" id="BPMNShape_hr">
        <omgdc:Bounds height="80.0" width="100.0" x="645.0" y="120.625"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-B951D5DB-EA64-4CD3-8F35-6463CA83A154" id="BPMNShape_sid-B951D5DB-EA64-4CD3-8F35-6463CA83A154">
        <omgdc:Bounds height="28.0" width="28.0" x="870.0" y="146.625"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-38DE5F46-A270-4060-87D2-3DB97997B861" id="BPMNShape_sid-38DE5F46-A270-4060-87D2-3DB97997B861">
        <omgdc:Bounds height="40.0" width="40.0" x="475.0" y="140.625"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="leader2" id="BPMNShape_leader2">
        <omgdc:Bounds height="80.0" width="100.0" x="445.0" y="315.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sid-EEF0DA1F-554E-4439-920E-0382841D7DE2" id="BPMNEdge_sid-EEF0DA1F-554E-4439-920E-0382841D7DE2" flowable:sourceDockerX="15.0" flowable:sourceDockerY="15.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="149.94976375101032" y="160.53977407408564"></omgdi:waypoint>
        <omgdi:waypoint x="194.99999999999565" y="160.28380681818183"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-D0666311-783F-49EC-95F7-13C648383566" id="BPMNEdge_sid-D0666311-783F-49EC-95F7-13C648383566" flowable:sourceDockerX="50.0" flowable:sourceDockerY="40.0" flowable:targetDockerX="20.0" flowable:targetDockerY="20.0">
        <omgdi:waypoint x="429.95000000000005" y="160.27146739130436"></omgdi:waypoint>
        <omgdi:waypoint x="475.0672391445236" y="160.5168918918919"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-5F44C7A8-94DB-4EA3-A77F-5DF3092F1C56" id="BPMNEdge_sid-5F44C7A8-94DB-4EA3-A77F-5DF3092F1C56" flowable:sourceDockerX="20.0" flowable:sourceDockerY="20.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="495.0" y="180.5698708060162"></omgdi:waypoint>
        <omgdi:waypoint x="495.0" y="315.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-ADD2E384-E8CC-4136-B881-93CFDC340A4E" id="BPMNEdge_sid-ADD2E384-E8CC-4136-B881-93CFDC340A4E" flowable:sourceDockerX="50.0" flowable:sourceDockerY="40.0" flowable:targetDockerX="14.0" flowable:targetDockerY="14.0">
        <omgdi:waypoint x="744.9499999999675" y="160.625"></omgdi:waypoint>
        <omgdi:waypoint x="870.0" y="160.625"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-753BBA2E-1D21-41EA-B44F-E8A0CDEE3D17" id="BPMNEdge_sid-753BBA2E-1D21-41EA-B44F-E8A0CDEE3D17" flowable:sourceDockerX="20.0" flowable:sourceDockerY="20.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="514.9450149924147" y="160.625"></omgdi:waypoint>
        <omgdi:waypoint x="645.0" y="160.625"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-5DE8C566-4721-456A-9240-CF4BF3DC7A61" id="BPMNEdge_sid-5DE8C566-4721-456A-9240-CF4BF3DC7A61" flowable:sourceDockerX="50.0" flowable:sourceDockerY="40.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="294.9499999999527" y="160.0"></omgdi:waypoint>
        <omgdi:waypoint x="329.99999999997203" y="160.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-6A8F54F5-165A-430F-A218-F8B6A054B784" id="BPMNEdge_sid-6A8F54F5-165A-430F-A218-F8B6A054B784" flowable:sourceDockerX="50.0" flowable:sourceDockerY="40.0" flowable:targetDockerX="50.0" flowable:targetDockerY="40.0">
        <omgdi:waypoint x="536.1061093247588" y="315.0"></omgdi:waypoint>
        <omgdi:waypoint x="653.8424437299035" y="200.575"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`

**Comment by hoslay757** [comment]
好的，我这边看一下，争取下个版本上这个功能

**Comment by zhoujh001** [comment]
谢谢啦

**Comment by hoslay757** [comment]
@zhoujh001  你好，你提的需求在V1.2.44版本已经实现了，已经发布了
http://dflow.ddei.top/examples/bpmnimport.html
